// Phase 1: Foundational Syllable Patterns
// CV and VC Syllables

import type { Phase } from "@/types/literacy"

export const phase1: Phase = {
  id: "phase-1",
  number: 1,
  title: "Foundational Syllable Patterns",
  description: "Learn CV and VC syllable patterns with natural pronunciation",
  lessons: [
    {
      id: "lesson-1-1",
      phaseId: "phase-1",
      title: "CV Syllables",
      description: "Learn Consonant-Vowel syllables",
      drills: [
        {
          type: "visual",
          items: [
            { id: "cv-ma", type: "syllable", content: "ma", audioHint: "Say this syllable: ma", syllablePattern: "CV" },
            { id: "cv-ba", type: "syllable", content: "ba", audioHint: "Say this syllable: ba", syllablePattern: "CV" },
            { id: "cv-go", type: "syllable", content: "go", audioHint: "Say this syllable: go", syllablePattern: "CV" },
            { id: "cv-me", type: "syllable", content: "me", audioHint: "Say this syllable: me", syllablePattern: "CV" },
            { id: "cv-so", type: "syllable", content: "so", audioHint: "Say this syllable: so", syllablePattern: "CV" },
            { id: "cv-da", type: "syllable", content: "da", audioHint: "Say this syllable: da", syllablePattern: "CV" },
            { id: "cv-no", type: "syllable", content: "no", audioHint: "Say this syllable: no", syllablePattern: "CV" },
            { id: "cv-be", type: "syllable", content: "be", audioHint: "Say this syllable: be", syllablePattern: "CV" },
            { id: "cv-to", type: "syllable", content: "to", audioHint: "Say this syllable: to", syllablePattern: "CV" },
            { id: "cv-la", type: "syllable", content: "la", audioHint: "Say this syllable: la", syllablePattern: "CV" },
          ],
          masteryThreshold: 90,
          consecutiveCorrect: 3,
        },
        {
          type: "auditory",
          items: [
            { id: "cv-ma-aud", type: "syllable", content: "ma", audioHint: "Say this syllable: ma", syllablePattern: "CV" },
            { id: "cv-ba-aud", type: "syllable", content: "ba", audioHint: "Say this syllable: ba", syllablePattern: "CV" },
            { id: "cv-go-aud", type: "syllable", content: "go", audioHint: "Say this syllable: go", syllablePattern: "CV" },
            { id: "cv-me-aud", type: "syllable", content: "me", audioHint: "Say this syllable: me", syllablePattern: "CV" },
            { id: "cv-so-aud", type: "syllable", content: "so", audioHint: "Say this syllable: so", syllablePattern: "CV" },
            { id: "cv-da-aud", type: "syllable", content: "da", audioHint: "Say this syllable: da", syllablePattern: "CV" },
            { id: "cv-no-aud", type: "syllable", content: "no", audioHint: "Say this syllable: no", syllablePattern: "CV" },
            { id: "cv-be-aud", type: "syllable", content: "be", audioHint: "Say this syllable: be", syllablePattern: "CV" },
          ],
          masteryThreshold: 85,
          consecutiveCorrect: 3,
        },
        {
          type: "air-writing",
          items: [
            { id: "cv-ma-air", type: "syllable", content: "ma", audioHint: "Say this syllable: ma", syllablePattern: "CV" },
            { id: "cv-ba-air", type: "syllable", content: "ba", audioHint: "Say this syllable: ba", syllablePattern: "CV" },
            { id: "cv-go-air", type: "syllable", content: "go", audioHint: "Say this syllable: go", syllablePattern: "CV" },
            { id: "cv-me-air", type: "syllable", content: "me", audioHint: "Say this syllable: me", syllablePattern: "CV" },
            { id: "cv-so-air", type: "syllable", content: "so", audioHint: "Say this syllable: so", syllablePattern: "CV" },
            { id: "cv-da-air", type: "syllable", content: "da", audioHint: "Say this syllable: da", syllablePattern: "CV" },
            { id: "cv-no-air", type: "syllable", content: "no", audioHint: "Say this syllable: no", syllablePattern: "CV" },
            { id: "cv-be-air", type: "syllable", content: "be", audioHint: "Say this syllable: be", syllablePattern: "CV" },
            { id: "cv-to-air", type: "syllable", content: "to", audioHint: "Say this syllable: to", syllablePattern: "CV" },
            { id: "cv-la-air", type: "syllable", content: "la", audioHint: "Say this syllable: la", syllablePattern: "CV" },
          ],
          masteryThreshold: 100,
          consecutiveCorrect: 1,
        },
      ],
    },
    {
      id: "lesson-1-2",
      phaseId: "phase-1",
      title: "VC Syllables",
      description: "Learn Vowel-Consonant syllables",
      drills: [
        {
          type: "visual",
          items: [
            { id: "vc-at", type: "syllable", content: "at", audioHint: "This syllable is: at", syllablePattern: "VC" },
            { id: "vc-in", type: "syllable", content: "in", audioHint: "This syllable is: in", syllablePattern: "VC" },
            { id: "vc-up", type: "syllable", content: "up", audioHint: "This syllable is: up", syllablePattern: "VC" },
            { id: "vc-an", type: "syllable", content: "an", audioHint: "This syllable is: an", syllablePattern: "VC" },
            { id: "vc-it", type: "syllable", content: "it", audioHint: "This syllable is: it", syllablePattern: "VC" },
            { id: "vc-on", type: "syllable", content: "on", audioHint: "This syllable is: on", syllablePattern: "VC" },
            { id: "vc-am", type: "syllable", content: "am", audioHint: "This syllable is: am", syllablePattern: "VC" },
            { id: "vc-ed", type: "syllable", content: "ed", audioHint: "This syllable is: ed", syllablePattern: "VC" },
            { id: "vc-op", type: "syllable", content: "op", audioHint: "This syllable is: op", syllablePattern: "VC" },
            { id: "vc-ub", type: "syllable", content: "ub", audioHint: "This syllable is: ub", syllablePattern: "VC" },
          ],
          masteryThreshold: 90,
          consecutiveCorrect: 3,
        },
        {
          type: "auditory",
          items: [
            { id: "vc-at-aud", type: "syllable", content: "at", audioHint: "This syllable is: at", syllablePattern: "VC" },
            { id: "vc-in-aud", type: "syllable", content: "in", audioHint: "This syllable is: in", syllablePattern: "VC" },
            { id: "vc-up-aud", type: "syllable", content: "up", audioHint: "This syllable is: up", syllablePattern: "VC" },
            { id: "vc-an-aud", type: "syllable", content: "an", audioHint: "This syllable is: an", syllablePattern: "VC" },
            { id: "vc-it-aud", type: "syllable", content: "it", audioHint: "This syllable is: it", syllablePattern: "VC" },
            { id: "vc-on-aud", type: "syllable", content: "on", audioHint: "This syllable is: on", syllablePattern: "VC" },
            { id: "vc-am-aud", type: "syllable", content: "am", audioHint: "This syllable is: am", syllablePattern: "VC" },
            { id: "vc-ed-aud", type: "syllable", content: "ed", audioHint: "This syllable is: ed", syllablePattern: "VC" },
          ],
          masteryThreshold: 85,
          consecutiveCorrect: 3,
        },
      ],
      prerequisites: ["lesson-1-1"],
    },
    {
      id: "lesson-1-3",
      phaseId: "phase-1",
      title: "Mixed CV and VC Practice",
      description: "Practice both CV and VC syllables together",
      drills: [
        {
          type: "visual",
          items: [
            { id: "mix-ma", type: "syllable", content: "ma", audioHint: "Say this syllable: ma", syllablePattern: "CV" },
            { id: "mix-at", type: "syllable", content: "at", audioHint: "This syllable is: at", syllablePattern: "VC" },
            { id: "mix-go", type: "syllable", content: "go", audioHint: "Say this syllable: go", syllablePattern: "CV" },
            { id: "mix-in", type: "syllable", content: "in", audioHint: "This syllable is: in", syllablePattern: "VC" },
            { id: "mix-be", type: "syllable", content: "be", audioHint: "Say this syllable: be", syllablePattern: "CV" },
            { id: "mix-up", type: "syllable", content: "up", audioHint: "This syllable is: up", syllablePattern: "VC" },
            { id: "mix-no", type: "syllable", content: "no", audioHint: "Say this syllable: no", syllablePattern: "CV" },
            { id: "mix-on", type: "syllable", content: "on", audioHint: "This syllable is: on", syllablePattern: "VC" },
          ],
          masteryThreshold: 90,
          consecutiveCorrect: 3,
        },
        {
          type: "auditory",
          items: [
            { id: "mix-ba-aud", type: "syllable", content: "ba", audioHint: "Say this syllable: ba", syllablePattern: "CV" },
            { id: "mix-it-aud", type: "syllable", content: "it", audioHint: "This syllable is: it", syllablePattern: "VC" },
            { id: "mix-so-aud", type: "syllable", content: "so", audioHint: "Say this syllable: so", syllablePattern: "CV" },
            { id: "mix-an-aud", type: "syllable", content: "an", audioHint: "This syllable is: an", syllablePattern: "VC" },
            { id: "mix-da-aud", type: "syllable", content: "da", audioHint: "Say this syllable: da", syllablePattern: "CV" },
            { id: "mix-am-aud", type: "syllable", content: "am", audioHint: "This syllable is: am", syllablePattern: "VC" },
          ],
          masteryThreshold: 85,
          consecutiveCorrect: 3,
        },
      ],
      prerequisites: ["lesson-1-2"],
    },
  ],
}
