// Phase 2: CVC Words (Closed Syllable Words)
// Real words and nonsense words (40% nonsense) organized by short vowel

import type { Phase } from "@/types/literacy"

export const phase2: Phase = {
  id: "phase-2",
  number: 2,
  title: "CVC Words",
  description: "Master CVC (Consonant-Vowel-Consonant) words with short vowels",
  prerequisites: ["phase-1"],
  lessons: [
    {
      id: "lesson-2-1",
      phaseId: "phase-2",
      title: "CVC with Short A",
      description: "Read CVC words with short /a/ sound",
      drills: [
        {
          type: "visual",
          items: [
            { id: "cvc-cat", type: "word", content: "cat", audioHint: "Read this word: cat", syllablePattern: "CVC", wordType: "real" },
            { id: "cvc-bat", type: "word", content: "bat", audioHint: "Read this word: bat", syllablePattern: "CVC", wordType: "real" },
            { id: "cvc-sat", type: "word", content: "sat", audioHint: "Read this word: sat", syllablePattern: "CVC", wordType: "real" },
            { id: "cvc-mat", type: "word", content: "mat", audioHint: "Read this word: mat", syllablePattern: "CVC", wordType: "real" },
            { id: "cvc-hat", type: "word", content: "hat", audioHint: "Read this word: hat", syllablePattern: "CVC", wordType: "real" },
            { id: "cvc-rat", type: "word", content: "rat", audioHint: "Read this word: rat", syllablePattern: "CVC", wordType: "real" },
            { id: "cvc-can", type: "word", content: "can", audioHint: "Read this word: can", syllablePattern: "CVC", wordType: "real" },
            { id: "cvc-man", type: "word", content: "man", audioHint: "Read this word: man", syllablePattern: "CVC", wordType: "real" },
            { id: "cvc-pan", type: "word", content: "pan", audioHint: "Read this word: pan", syllablePattern: "CVC", wordType: "real" },
            { id: "cvc-tan", type: "word", content: "tan", audioHint: "Read this word: tan", syllablePattern: "CVC", wordType: "real" },
            // Nonsense words (40%)
            { id: "cvc-dat", type: "word", content: "dat", audioHint: "What word is this? dat", syllablePattern: "CVC", wordType: "nonsense" },
            { id: "cvc-gat", type: "word", content: "gat", audioHint: "What word is this? gat", syllablePattern: "CVC", wordType: "nonsense" },
            { id: "cvc-lat", type: "word", content: "lat", audioHint: "What word is this? lat", syllablePattern: "CVC", wordType: "nonsense" },
            { id: "cvc-vat", type: "word", content: "vat", audioHint: "What word is this? vat", syllablePattern: "CVC", wordType: "nonsense" },
            { id: "cvc-zan", type: "word", content: "zan", audioHint: "What word is this? zan", syllablePattern: "CVC", wordType: "nonsense" },
          ],
          masteryThreshold: 90,
          consecutiveCorrect: 3,
        },
        {
          type: "blending",
          items: [],
          blendingWords: [
            { word: "cat", type: "real", pattern: "CVC" },
            { word: "bat", type: "real", pattern: "CVC" },
            { word: "sat", type: "real", pattern: "CVC" },
            { word: "mat", type: "real", pattern: "CVC" },
            { word: "hat", type: "real", pattern: "CVC" },
            { word: "rat", type: "real", pattern: "CVC" },
            { word: "dat", type: "nonsense", pattern: "CVC" },
            { word: "gat", type: "nonsense", pattern: "CVC" },
            { word: "lat", type: "nonsense", pattern: "CVC" },
          ],
          masteryThreshold: 85,
          consecutiveCorrect: 3,
        },
      ],
    },
    {
      id: "lesson-2-2",
      phaseId: "phase-2",
      title: "CVC with Short I",
      description: "Read CVC words with short /i/ sound",
      drills: [
        {
          type: "visual",
          items: [
            { id: "cvc-sit", type: "word", content: "sit", audioHint: "Read this word: sit", syllablePattern: "CVC", wordType: "real" },
            { id: "cvc-bit", type: "word", content: "bit", audioHint: "Read this word: bit", syllablePattern: "CVC", wordType: "real" },
            { id: "cvc-hit", type: "word", content: "hit", audioHint: "Read this word: hit", syllablePattern: "CVC", wordType: "real" },
            { id: "cvc-pit", type: "word", content: "pit", audioHint: "Read this word: pit", syllablePattern: "CVC", wordType: "real" },
            { id: "cvc-fit", type: "word", content: "fit", audioHint: "Read this word: fit", syllablePattern: "CVC", wordType: "real" },
            { id: "cvc-pin", type: "word", content: "pin", audioHint: "Read this word: pin", syllablePattern: "CVC", wordType: "real" },
            { id: "cvc-tin", type: "word", content: "tin", audioHint: "Read this word: tin", syllablePattern: "CVC", wordType: "real" },
            { id: "cvc-win", type: "word", content: "win", audioHint: "Read this word: win", syllablePattern: "CVC", wordType: "real" },
            { id: "cvc-fin", type: "word", content: "fin", audioHint: "Read this word: fin", syllablePattern: "CVC", wordType: "real" },
            { id: "cvc-dig", type: "word", content: "dig", audioHint: "Read this word: dig", syllablePattern: "CVC", wordType: "real" },
            // Nonsense words (40%)
            { id: "cvc-dit", type: "word", content: "dit", audioHint: "What word is this? dit", syllablePattern: "CVC", wordType: "nonsense" },
            { id: "cvc-git", type: "word", content: "git", audioHint: "What word is this? git", syllablePattern: "CVC", wordType: "nonsense" },
            { id: "cvc-mit", type: "word", content: "mit", audioHint: "What word is this? mit", syllablePattern: "CVC", wordType: "nonsense" },
            { id: "cvc-vin", type: "word", content: "vin", audioHint: "What word is this? vin", syllablePattern: "CVC", wordType: "nonsense" },
            { id: "cvc-zit", type: "word", content: "zit", audioHint: "What word is this? zit", syllablePattern: "CVC", wordType: "nonsense" },
          ],
          masteryThreshold: 90,
          consecutiveCorrect: 3,
        },
        {
          type: "blending",
          items: [],
          blendingWords: [
            { word: "sit", type: "real", pattern: "CVC" },
            { word: "bit", type: "real", pattern: "CVC" },
            { word: "hit", type: "real", pattern: "CVC" },
            { word: "pit", type: "real", pattern: "CVC" },
            { word: "fit", type: "real", pattern: "CVC" },
            { word: "dit", type: "nonsense", pattern: "CVC" },
            { word: "git", type: "nonsense", pattern: "CVC" },
            { word: "mit", type: "nonsense", pattern: "CVC" },
          ],
          masteryThreshold: 85,
          consecutiveCorrect: 3,
        },
      ],
      prerequisites: ["lesson-2-1"],
    },
    {
      id: "lesson-2-3",
      phaseId: "phase-2",
      title: "CVC with Short O",
      description: "Read CVC words with short /o/ sound",
      drills: [
        {
          type: "visual",
          items: [
            { id: "cvc-hot", type: "word", content: "hot", audioHint: "Read this word: hot", syllablePattern: "CVC", wordType: "real" },
            { id: "cvc-pot", type: "word", content: "pot", audioHint: "Read this word: pot", syllablePattern: "CVC", wordType: "real" },
            { id: "cvc-dot", type: "word", content: "dot", audioHint: "Read this word: dot", syllablePattern: "CVC", wordType: "real" },
            { id: "cvc-got", type: "word", content: "got", audioHint: "Read this word: got", syllablePattern: "CVC", wordType: "real" },
            { id: "cvc-lot", type: "word", content: "lot", audioHint: "Read this word: lot", syllablePattern: "CVC", wordType: "real" },
            { id: "cvc-cop", type: "word", content: "cop", audioHint: "Read this word: cop", syllablePattern: "CVC", wordType: "real" },
            { id: "cvc-hop", type: "word", content: "hop", audioHint: "Read this word: hop", syllablePattern: "CVC", wordType: "real" },
            { id: "cvc-mop", type: "word", content: "mop", audioHint: "Read this word: mop", syllablePattern: "CVC", wordType: "real" },
            { id: "cvc-top", type: "word", content: "top", audioHint: "Read this word: top", syllablePattern: "CVC", wordType: "real" },
            { id: "cvc-dog", type: "word", content: "dog", audioHint: "Read this word: dog", syllablePattern: "CVC", wordType: "real" },
            // Nonsense words (40%)
            { id: "cvc-bot", type: "word", content: "bot", audioHint: "What word is this? bot", syllablePattern: "CVC", wordType: "nonsense" },
            { id: "cvc-jot", type: "word", content: "jot", audioHint: "What word is this? jot", syllablePattern: "CVC", wordType: "nonsense" },
            { id: "cvc-fod", type: "word", content: "fod", audioHint: "What word is this? fod", syllablePattern: "CVC", wordType: "nonsense" },
            { id: "cvc-gop", type: "word", content: "gop", audioHint: "What word is this? gop", syllablePattern: "CVC", wordType: "nonsense" },
          ],
          masteryThreshold: 90,
          consecutiveCorrect: 3,
        },
        {
          type: "blending",
          items: [],
          blendingWords: [
            { word: "hot", type: "real", pattern: "CVC" },
            { word: "pot", type: "real", pattern: "CVC" },
            { word: "dot", type: "real", pattern: "CVC" },
            { word: "got", type: "real", pattern: "CVC" },
            { word: "lot", type: "real", pattern: "CVC" },
            { word: "bot", type: "nonsense", pattern: "CVC" },
            { word: "jot", type: "nonsense", pattern: "CVC" },
          ],
          masteryThreshold: 85,
          consecutiveCorrect: 3,
        },
      ],
      prerequisites: ["lesson-2-2"],
    },
    {
      id: "lesson-2-4",
      phaseId: "phase-2",
      title: "CVC with Short U",
      description: "Read CVC words with short /u/ sound",
      drills: [
        {
          type: "visual",
          items: [
            { id: "cvc-cup", type: "word", content: "cup", audioHint: "Read this word: cup", syllablePattern: "CVC", wordType: "real" },
            { id: "cvc-pup", type: "word", content: "pup", audioHint: "Read this word: pup", syllablePattern: "CVC", wordType: "real" },
            { id: "cvc-sun", type: "word", content: "sun", audioHint: "Read this word: sun", syllablePattern: "CVC", wordType: "real" },
            { id: "cvc-run", type: "word", content: "run", audioHint: "Read this word: run", syllablePattern: "CVC", wordType: "real" },
            { id: "cvc-fun", type: "word", content: "fun", audioHint: "Read this word: fun", syllablePattern: "CVC", wordType: "real" },
            { id: "cvc-bug", type: "word", content: "bug", audioHint: "Read this word: bug", syllablePattern: "CVC", wordType: "real" },
            { id: "cvc-hug", type: "word", content: "hug", audioHint: "Read this word: hug", syllablePattern: "CVC", wordType: "real" },
            { id: "cvc-mug", type: "word", content: "mug", audioHint: "Read this word: mug", syllablePattern: "CVC", wordType: "real" },
            { id: "cvc-rug", type: "word", content: "rug", audioHint: "Read this word: rug", syllablePattern: "CVC", wordType: "real" },
            { id: "cvc-tub", type: "word", content: "tub", audioHint: "Read this word: tub", syllablePattern: "CVC", wordType: "real" },
            // Nonsense words (40%)
            { id: "cvc-bup", type: "word", content: "bup", audioHint: "What word is this? bup", syllablePattern: "CVC", wordType: "nonsense" },
            { id: "cvc-tun", type: "word", content: "tun", audioHint: "What word is this? tun", syllablePattern: "CVC", wordType: "nonsense" },
            { id: "cvc-gub", type: "word", content: "gub", audioHint: "What word is this? gub", syllablePattern: "CVC", wordType: "nonsense" },
            { id: "cvc-zup", type: "word", content: "zup", audioHint: "What word is this? zup", syllablePattern: "CVC", wordType: "nonsense" },
          ],
          masteryThreshold: 90,
          consecutiveCorrect: 3,
        },
        {
          type: "blending",
          items: [],
          blendingWords: [
            { word: "cup", type: "real", pattern: "CVC" },
            { word: "pup", type: "real", pattern: "CVC" },
            { word: "sun", type: "real", pattern: "CVC" },
            { word: "run", type: "real", pattern: "CVC" },
            { word: "fun", type: "real", pattern: "CVC" },
            { word: "bup", type: "nonsense", pattern: "CVC" },
            { word: "tun", type: "nonsense", pattern: "CVC" },
          ],
          masteryThreshold: 85,
          consecutiveCorrect: 3,
        },
      ],
      prerequisites: ["lesson-2-3"],
    },
    {
      id: "lesson-2-5",
      phaseId: "phase-2",
      title: "CVC with Short E",
      description: "Read CVC words with short /e/ sound",
      drills: [
        {
          type: "visual",
          items: [
            { id: "cvc-bed", type: "word", content: "bed", audioHint: "Read this word: bed", syllablePattern: "CVC", wordType: "real" },
            { id: "cvc-red", type: "word", content: "red", audioHint: "Read this word: red", syllablePattern: "CVC", wordType: "real" },
            { id: "cvc-fed", type: "word", content: "fed", audioHint: "Read this word: fed", syllablePattern: "CVC", wordType: "real" },
            { id: "cvc-led", type: "word", content: "led", audioHint: "Read this word: led", syllablePattern: "CVC", wordType: "real" },
            { id: "cvc-wed", type: "word", content: "wed", audioHint: "Read this word: wed", syllablePattern: "CVC", wordType: "real" },
            { id: "cvc-pet", type: "word", content: "pet", audioHint: "Read this word: pet", syllablePattern: "CVC", wordType: "real" },
            { id: "cvc-get", type: "word", content: "get", audioHint: "Read this word: get", syllablePattern: "CVC", wordType: "real" },
            { id: "cvc-set", type: "word", content: "set", audioHint: "Read this word: set", syllablePattern: "CVC", wordType: "real" },
            { id: "cvc-wet", type: "word", content: "wet", audioHint: "Read this word: wet", syllablePattern: "CVC", wordType: "real" },
            { id: "cvc-hen", type: "word", content: "hen", audioHint: "Read this word: hen", syllablePattern: "CVC", wordType: "real" },
            // Nonsense words (40%)
            { id: "cvc-ped", type: "word", content: "ped", audioHint: "What word is this? ped", syllablePattern: "CVC", wordType: "nonsense" },
            { id: "cvc-ged", type: "word", content: "ged", audioHint: "What word is this? ged", syllablePattern: "CVC", wordType: "nonsense" },
            { id: "cvc-bef", type: "word", content: "bef", audioHint: "What word is this? bef", syllablePattern: "CVC", wordType: "nonsense" },
            { id: "cvc-ven", type: "word", content: "ven", audioHint: "What word is this? ven", syllablePattern: "CVC", wordType: "nonsense" },
          ],
          masteryThreshold: 90,
          consecutiveCorrect: 3,
        },
        {
          type: "blending",
          items: [],
          blendingWords: [
            { word: "bed", type: "real", pattern: "CVC" },
            { word: "red", type: "real", pattern: "CVC" },
            { word: "fed", type: "real", pattern: "CVC" },
            { word: "led", type: "real", pattern: "CVC" },
            { word: "wed", type: "real", pattern: "CVC" },
            { word: "ped", type: "nonsense", pattern: "CVC" },
            { word: "ged", type: "nonsense", pattern: "CVC" },
          ],
          masteryThreshold: 85,
          consecutiveCorrect: 3,
        },
      ],
      prerequisites: ["lesson-2-4"],
    },
  ],
}
