// Phase 3: CVC-e (Magic E / Silent E)
// Long vowel words with silent E pattern

import type { Phase } from "@/types/literacy"

export const phase3: Phase = {
  id: "phase-3",
  number: 3,
  title: "CVC-e (Magic E)",
  description: "Master CVC-e words with long vowels and silent E",
  prerequisites: ["phase-2"],
  lessons: [
    {
      id: "lesson-3-1",
      phaseId: "phase-3",
      title: "CVCe with Long A (a_e)",
      description: "Read words with long A and silent E",
      drills: [
        {
          type: "visual",
          items: [
            { id: "cvce-cake", type: "word", content: "cake", audioHint: "This word is cake. The E at the end is silent and makes the A say its name.", syllablePattern: "CVC-e", wordType: "real" },
            { id: "cvce-make", type: "word", content: "make", audioHint: "This word is make. The E at the end is silent and makes the A say its name.", syllablePattern: "CVC-e", wordType: "real" },
            { id: "cvce-lake", type: "word", content: "lake", audioHint: "This word is lake. The silent E makes A say its name.", syllablePattern: "CVC-e", wordType: "real" },
            { id: "cvce-bake", type: "word", content: "bake", audioHint: "This word is bake. The silent E makes A say its name.", syllablePattern: "CVC-e", wordType: "real" },
            { id: "cvce-take", type: "word", content: "take", audioHint: "This word is take. The silent E makes A say its name.", syllablePattern: "CVC-e", wordType: "real" },
            { id: "cvce-wake", type: "word", content: "wake", audioHint: "This word is wake. The E is silent.", syllablePattern: "CVC-e", wordType: "real" },
            { id: "cvce-name", type: "word", content: "name", audioHint: "This word is name. The E is silent.", syllablePattern: "CVC-e", wordType: "real" },
            { id: "cvce-game", type: "word", content: "game", audioHint: "This word is game. The E is silent.", syllablePattern: "CVC-e", wordType: "real" },
            { id: "cvce-same", type: "word", content: "same", audioHint: "This word is same. The E is silent.", syllablePattern: "CVC-e", wordType: "real" },
            { id: "cvce-late", type: "word", content: "late", audioHint: "This word is late. The E is silent.", syllablePattern: "CVC-e", wordType: "real" },
          ],
          masteryThreshold: 90,
          consecutiveCorrect: 3,
        },
        {
          type: "blending",
          items: [],
          blendingWords: [
            { word: "cake", type: "real", pattern: "CVC-e" },
            { word: "make", type: "real", pattern: "CVC-e" },
            { word: "lake", type: "real", pattern: "CVC-e" },
            { word: "bake", type: "real", pattern: "CVC-e" },
            { word: "take", type: "real", pattern: "CVC-e" },
            { word: "wake", type: "real", pattern: "CVC-e" },
            { word: "name", type: "real", pattern: "CVC-e" },
            { word: "game", type: "real", pattern: "CVC-e" },
          ],
          masteryThreshold: 85,
          consecutiveCorrect: 3,
        },
      ],
    },
    {
      id: "lesson-3-2",
      phaseId: "phase-3",
      title: "CVCe with Long I (i_e)",
      description: "Read words with long I and silent E",
      drills: [
        {
          type: "visual",
          items: [
            { id: "cvce-bike", type: "word", content: "bike", audioHint: "This word is bike. The silent E makes I say its name.", syllablePattern: "CVC-e", wordType: "real" },
            { id: "cvce-like", type: "word", content: "like", audioHint: "This word is like. The silent E makes I say its name.", syllablePattern: "CVC-e", wordType: "real" },
            { id: "cvce-hike", type: "word", content: "hike", audioHint: "This word is hike. The silent E makes I say its name.", syllablePattern: "CVC-e", wordType: "real" },
            { id: "cvce-time", type: "word", content: "time", audioHint: "This word is time. The E is silent.", syllablePattern: "CVC-e", wordType: "real" },
            { id: "cvce-dime", type: "word", content: "dime", audioHint: "This word is dime. The E is silent.", syllablePattern: "CVC-e", wordType: "real" },
            { id: "cvce-lime", type: "word", content: "lime", audioHint: "This word is lime. The E is silent.", syllablePattern: "CVC-e", wordType: "real" },
            { id: "cvce-ride", type: "word", content: "ride", audioHint: "This word is ride. The E is silent.", syllablePattern: "CVC-e", wordType: "real" },
            { id: "cvce-hide", type: "word", content: "hide", audioHint: "This word is hide. The E is silent.", syllablePattern: "CVC-e", wordType: "real" },
            { id: "cvce-side", type: "word", content: "side", audioHint: "This word is side. The E is silent.", syllablePattern: "CVC-e", wordType: "real" },
            { id: "cvce-fine", type: "word", content: "fine", audioHint: "This word is fine. The E is silent.", syllablePattern: "CVC-e", wordType: "real" },
          ],
          masteryThreshold: 90,
          consecutiveCorrect: 3,
        },
        {
          type: "blending",
          items: [],
          blendingWords: [
            { word: "bike", type: "real", pattern: "CVC-e" },
            { word: "like", type: "real", pattern: "CVC-e" },
            { word: "hike", type: "real", pattern: "CVC-e" },
            { word: "time", type: "real", pattern: "CVC-e" },
            { word: "dime", type: "real", pattern: "CVC-e" },
            { word: "ride", type: "real", pattern: "CVC-e" },
            { word: "hide", type: "real", pattern: "CVC-e" },
            { word: "fine", type: "real", pattern: "CVC-e" },
          ],
          masteryThreshold: 85,
          consecutiveCorrect: 3,
        },
      ],
      prerequisites: ["lesson-3-1"],
    },
    {
      id: "lesson-3-3",
      phaseId: "phase-3",
      title: "CVCe with Long O (o_e)",
      description: "Read words with long O and silent E",
      drills: [
        {
          type: "visual",
          items: [
            { id: "cvce-home", type: "word", content: "home", audioHint: "Listen to the word: home. The E is silent.", syllablePattern: "CVC-e", wordType: "real" },
            { id: "cvce-bone", type: "word", content: "bone", audioHint: "This word is bone. The E is silent.", syllablePattern: "CVC-e", wordType: "real" },
            { id: "cvce-tone", type: "word", content: "tone", audioHint: "This word is tone. The E is silent.", syllablePattern: "CVC-e", wordType: "real" },
            { id: "cvce-note", type: "word", content: "note", audioHint: "This word is note. The E is silent.", syllablePattern: "CVC-e", wordType: "real" },
            { id: "cvce-vote", type: "word", content: "vote", audioHint: "This word is vote. The E is silent.", syllablePattern: "CVC-e", wordType: "real" },
            { id: "cvce-hope", type: "word", content: "hope", audioHint: "This word is hope. The E is silent.", syllablePattern: "CVC-e", wordType: "real" },
            { id: "cvce-rope", type: "word", content: "rope", audioHint: "This word is rope. The E is silent.", syllablePattern: "CVC-e", wordType: "real" },
            { id: "cvce-cone", type: "word", content: "cone", audioHint: "This word is cone. The E is silent.", syllablePattern: "CVC-e", wordType: "real" },
            { id: "cvce-zone", type: "word", content: "zone", audioHint: "This word is zone. The E is silent.", syllablePattern: "CVC-e", wordType: "real" },
            { id: "cvce-pole", type: "word", content: "pole", audioHint: "This word is pole. The E is silent.", syllablePattern: "CVC-e", wordType: "real" },
          ],
          masteryThreshold: 90,
          consecutiveCorrect: 3,
        },
        {
          type: "blending",
          items: [],
          blendingWords: [
            { word: "home", type: "real", pattern: "CVC-e" },
            { word: "bone", type: "real", pattern: "CVC-e" },
            { word: "tone", type: "real", pattern: "CVC-e" },
            { word: "note", type: "real", pattern: "CVC-e" },
            { word: "vote", type: "real", pattern: "CVC-e" },
            { word: "hope", type: "real", pattern: "CVC-e" },
            { word: "rope", type: "real", pattern: "CVC-e" },
            { word: "cone", type: "real", pattern: "CVC-e" },
          ],
          masteryThreshold: 85,
          consecutiveCorrect: 3,
        },
      ],
      prerequisites: ["lesson-3-2"],
    },
    {
      id: "lesson-3-4",
      phaseId: "phase-3",
      title: "CVCe with Long U (u_e)",
      description: "Read words with long U and silent E",
      drills: [
        {
          type: "visual",
          items: [
            { id: "cvce-cute", type: "word", content: "cute", audioHint: "This word is cute.", syllablePattern: "CVC-e", wordType: "real" },
            { id: "cvce-mute", type: "word", content: "mute", audioHint: "This word is mute.", syllablePattern: "CVC-e", wordType: "real" },
            { id: "cvce-tube", type: "word", content: "tube", audioHint: "This word is tube.", syllablePattern: "CVC-e", wordType: "real" },
            { id: "cvce-cube", type: "word", content: "cube", audioHint: "This word is cube.", syllablePattern: "CVC-e", wordType: "real" },
            { id: "cvce-tune", type: "word", content: "tune", audioHint: "This word is tune.", syllablePattern: "CVC-e", wordType: "real" },
            { id: "cvce-dune", type: "word", content: "dune", audioHint: "This word is dune.", syllablePattern: "CVC-e", wordType: "real" },
            { id: "cvce-fuse", type: "word", content: "fuse", audioHint: "This word is fuse.", syllablePattern: "CVC-e", wordType: "real" },
            { id: "cvce-use", type: "word", content: "use", audioHint: "This word is use.", syllablePattern: "CVC-e", wordType: "real" },
            { id: "cvce-huge", type: "word", content: "huge", audioHint: "This word is huge.", syllablePattern: "CVC-e", wordType: "real" },
            { id: "cvce-rude", type: "word", content: "rude", audioHint: "This word is rude.", syllablePattern: "CVC-e", wordType: "real" },
          ],
          masteryThreshold: 90,
          consecutiveCorrect: 3,
        },
        {
          type: "blending",
          items: [],
          blendingWords: [
            { word: "cute", type: "real", pattern: "CVC-e" },
            { word: "mute", type: "real", pattern: "CVC-e" },
            { word: "tube", type: "real", pattern: "CVC-e" },
            { word: "cube", type: "real", pattern: "CVC-e" },
            { word: "tune", type: "real", pattern: "CVC-e" },
            { word: "dune", type: "real", pattern: "CVC-e" },
            { word: "fuse", type: "real", pattern: "CVC-e" },
            { word: "huge", type: "real", pattern: "CVC-e" },
          ],
          masteryThreshold: 85,
          consecutiveCorrect: 3,
        },
      ],
      prerequisites: ["lesson-3-3"],
    },
  ],
}
