// Phase 2: CVCV Patterns (Two-Syllable Words)
// Building multi-syllable words from CV syllables learned in Phase 1

import type { Phase } from "@/types/literacy"

export const phase2: Phase = {
  id: "phase-2",
  number: 2,
  title: "CVCV Patterns",
  description: "Combine CV syllables to build two-syllable words",
  prerequisites: ["phase-1"],
  lessons: [
    {
      id: "lesson-2-1",
      phaseId: "phase-2",
      title: "CVCV Patterns",
      description: "Learn simple two-syllable words like mama, dada, baby",
      drills: [
        {
          type: "visual",
          items: [
            { id: "cvcv-mama", type: "word", content: "mama", audioHint: "Read this word: mama", syllablePattern: "CVCV", wordType: "real" },
            { id: "cvcv-dada", type: "word", content: "dada", audioHint: "Read this word: dada", syllablePattern: "CVCV", wordType: "real" },
            { id: "cvcv-baby", type: "word", content: "baby", audioHint: "Read this word: baby", syllablePattern: "CVCV", wordType: "real" },
            { id: "cvcv-taco", type: "word", content: "taco", audioHint: "Read this word: taco", syllablePattern: "CVCV", wordType: "real" },
            { id: "cvcv-sofa", type: "word", content: "sofa", audioHint: "Read this word: sofa", syllablePattern: "CVCV", wordType: "real" },
            { id: "cvcv-pony", type: "word", content: "pony", audioHint: "Read this word: pony", syllablePattern: "CVCV", wordType: "real" },
            { id: "cvcv-navy", type: "word", content: "navy", audioHint: "Read this word: navy", syllablePattern: "CVCV", wordType: "real" },
            { id: "cvcv-lady", type: "word", content: "lady", audioHint: "Read this word: lady", syllablePattern: "CVCV", wordType: "real" },
            { id: "cvcv-lazy", type: "word", content: "lazy", audioHint: "Read this word: lazy", syllablePattern: "CVCV", wordType: "real" },
            { id: "cvcv-crazy", type: "word", content: "crazy", audioHint: "Read this word: crazy", syllablePattern: "CVCV", wordType: "real" },
          ],
          masteryThreshold: 90,
          consecutiveCorrect: 3,
        },
        {
          type: "auditory",
          items: [
            { id: "cvcv-papa", type: "word", content: "papa", audioHint: "Say it with me: papa", syllablePattern: "CVCV", wordType: "real" },
            { id: "cvcv-nana", type: "word", content: "nana", audioHint: "Say it with me: nana", syllablePattern: "CVCV", wordType: "real" },
            { id: "cvcv-boba", type: "word", content: "boba", audioHint: "Say it with me: boba", syllablePattern: "CVCV", wordType: "real" },
            { id: "cvcv-soda", type: "word", content: "soda", audioHint: "Say it with me: soda", syllablePattern: "CVCV", wordType: "real" },
          ],
          masteryThreshold: 85,
          consecutiveCorrect: 3,
        },
        {
          type: "blending",
          items: [],
          blendingWords: [
            { word: "mama", type: "real", pattern: "CVCV" },
            { word: "dada", type: "real", pattern: "CVCV" },
            { word: "baby", type: "real", pattern: "CVCV" },
            { word: "taco", type: "real", pattern: "CVCV" },
            { word: "sofa", type: "real", pattern: "CVCV" },
            { word: "pony", type: "real", pattern: "CVCV" },
          ],
          masteryThreshold: 85,
          consecutiveCorrect: 3,
        },
      ],
    },
    {
      id: "lesson-2-2",
      phaseId: "phase-2",
      title: "Building Words from CV+VC Combinations",
      description: "Combine CV syllables with VC endings to make words",
      drills: [
        {
          type: "visual",
          items: [
            { id: "cv-vc-robin", type: "word", content: "robin", audioHint: "Read this word: robin", syllablePattern: "CVCV", wordType: "real" },
            { id: "cv-vc-cabin", type: "word", content: "cabin", audioHint: "Read this word: cabin", syllablePattern: "CVCV", wordType: "real" },
            { id: "cv-vc-wagon", type: "word", content: "wagon", audioHint: "Read this word: wagon", syllablePattern: "CVCV", wordType: "real" },
            { id: "cv-vc-melon", type: "word", content: "melon", audioHint: "Read this word: melon", syllablePattern: "CVCV", wordType: "real" },
            { id: "cv-vc-lemon", type: "word", content: "lemon", audioHint: "Read this word: lemon", syllablePattern: "CVCV", wordType: "real" },
            { id: "cv-vc-dragon", type: "word", content: "dragon", audioHint: "Read this word: dragon", syllablePattern: "CVCV", wordType: "real" },
            { id: "cv-vc-tulip", type: "word", content: "tulip", audioHint: "Read this word: tulip", syllablePattern: "CVCV", wordType: "real" },
            { id: "cv-vc-music", type: "word", content: "music", audioHint: "Read this word: music", syllablePattern: "CVCV", wordType: "real" },
          ],
          masteryThreshold: 90,
          consecutiveCorrect: 3,
        },
        {
          type: "auditory",
          items: [
            { id: "cv-vc-basin", type: "word", content: "basin", audioHint: "Say it with me: basin", syllablePattern: "CVCV", wordType: "real" },
            { id: "cv-vc-robot", type: "word", content: "robot", audioHint: "Say it with me: robot", syllablePattern: "CVCV", wordType: "real" },
            { id: "cv-vc-salad", type: "word", content: "salad", audioHint: "Say it with me: salad", syllablePattern: "CVCV", wordType: "real" },
            { id: "cv-vc-pupil", type: "word", content: "pupil", audioHint: "Say it with me: pupil", syllablePattern: "CVCV", wordType: "real" },
          ],
          masteryThreshold: 85,
          consecutiveCorrect: 3,
        },
        {
          type: "blending",
          items: [],
          blendingWords: [
            { word: "robin", type: "real", pattern: "CVCV" },
            { word: "cabin", type: "real", pattern: "CVCV" },
            { word: "wagon", type: "real", pattern: "CVCV" },
            { word: "melon", type: "real", pattern: "CVCV" },
            { word: "lemon", type: "real", pattern: "CVCV" },
            { word: "dragon", type: "real", pattern: "CVCV" },
          ],
          masteryThreshold: 85,
          consecutiveCorrect: 3,
        },
      ],
      prerequisites: ["lesson-2-1"],
    },
    {
      id: "lesson-2-3",
      phaseId: "phase-2",
      title: "Blending Practice with CVCV Words",
      description: "Practice blending two-syllable CVCV words",
      drills: [
        {
          type: "visual",
          items: [
            { id: "cvcv-tiger", type: "word", content: "tiger", audioHint: "Read this word: tiger", syllablePattern: "CVCV", wordType: "real" },
            { id: "cvcv-pizza", type: "word", content: "pizza", audioHint: "Read this word: pizza", syllablePattern: "CVCV", wordType: "real" },
            { id: "cvcv-bacon", type: "word", content: "bacon", audioHint: "Read this word: bacon", syllablePattern: "CVCV", wordType: "real" },
            { id: "cvcv-paper", type: "word", content: "paper", audioHint: "Read this word: paper", syllablePattern: "CVCV", wordType: "real" },
            { id: "cvcv-spider", type: "word", content: "spider", audioHint: "Read this word: spider", syllablePattern: "CVCV", wordType: "real" },
            { id: "cvcv-panda", type: "word", content: "panda", audioHint: "Read this word: panda", syllablePattern: "CVCV", wordType: "real" },
            { id: "cvcv-zebra", type: "word", content: "zebra", audioHint: "Read this word: zebra", syllablePattern: "CVCV", wordType: "real" },
            { id: "cvcv-human", type: "word", content: "human", audioHint: "Read this word: human", syllablePattern: "CVCV", wordType: "real" },
          ],
          masteryThreshold: 90,
          consecutiveCorrect: 3,
        },
        {
          type: "blending",
          items: [],
          blendingWords: [
            { word: "mama", type: "real", pattern: "CVCV" },
            { word: "dada", type: "real", pattern: "CVCV" },
            { word: "baby", type: "real", pattern: "CVCV" },
            { word: "taco", type: "real", pattern: "CVCV" },
            { word: "sofa", type: "real", pattern: "CVCV" },
            { word: "robin", type: "real", pattern: "CVCV" },
            { word: "cabin", type: "real", pattern: "CVCV" },
            { word: "wagon", type: "real", pattern: "CVCV" },
            { word: "tiger", type: "real", pattern: "CVCV" },
            { word: "pizza", type: "real", pattern: "CVCV" },
            { word: "bacon", type: "real", pattern: "CVCV" },
            { word: "paper", type: "real", pattern: "CVCV" },
          ],
          masteryThreshold: 85,
          consecutiveCorrect: 3,
        },
      ],
      prerequisites: ["lesson-2-2"],
    },
  ],
}
