import type { CommunicationButton } from "@/types"

export const defaultButtons: CommunicationButton[] = [
  // Social/Greetings
  {
    id: "hey",
    label: "Hey!",
    text: "Hey! Come check this out with me!",
    category: "Social",
    color: "#14b8a6",
    icon: "wave",
    emotion: "excited",
    contextHint: "A child excitedly waving to get someone's attention, pointing at something interesting",
  },
  {
    id: "good-morning",
    label: "Good morning",
    text: "Good morning! I hope you have a great day!",
    category: "Social",
    color: "#14b8a6",
    icon: "sun",
    emotion: "happy",
    contextHint: "A child waking up in bed, stretching with sunshine coming through the window",
  },
  {
    id: "look",
    label: "Look!",
    text: "Look at this! Isn't it amazing?",
    category: "Social",
    color: "#14b8a6",
    icon: "eye",
    emotion: "excited",
    contextHint: "A child pointing excitedly at something wonderful, eyes wide with amazement",
  },
  {
    id: "this-is-fun",
    label: "This is fun",
    text: "This is so much fun! I love it!",
    category: "Social",
    color: "#14b8a6",
    icon: "smile",
    emotion: "happy",
    contextHint: "A child playing and laughing, having a wonderful time with a favorite activity",
  },
  {
    id: "bye",
    label: "Bye!",
    text: "Bye bye! See you later!",
    category: "Social",
    color: "#14b8a6",
    icon: "bye",
    emotion: "happy",
    contextHint: "A child waving goodbye with a smile as someone leaves",
  },
  // Requests
  {
    id: "can-i-have",
    label: "Can I have...",
    text: "Excuse me, can I please have some of that?",
    category: "Requests",
    color: "#f97316",
    icon: "please",
    emotion: "neutral",
    contextHint: "A child politely pointing at something they want, looking hopeful",
  },
  {
    id: "hungry",
    label: "I'm hungry",
    text: "I'm feeling hungry. Can I have something to eat?",
    category: "Requests",
    color: "#f97316",
    icon: "hungry",
    emotion: "neutral",
    contextHint: "A child holding their tummy, looking at food on the table",
  },
  {
    id: "hungry-breakfast",
    label: "I'm hungry for breakfast",
    text: "I'm hungry for breakfast. Can I have something to eat?",
    category: "Requests",
    color: "#f97316",
    icon: "hungry",
    emotion: "neutral",
    contextHint:
      "A child sitting at the breakfast table in the morning, looking at cereal and toast, holding their tummy",
  },
  {
    id: "bathroom",
    label: "I need to use the bathroom",
    text: "I need to use the bathroom please.",
    category: "Requests",
    color: "#f97316",
    icon: "wait",
    emotion: "neutral",
    contextHint: "A child doing the potty dance, crossing their legs, pointing toward the bathroom door",
  },
  {
    id: "snack",
    label: "Can I have a snack?",
    text: "Can I have a snack please? I'm a little hungry.",
    category: "Requests",
    color: "#f97316",
    icon: "hungry",
    emotion: "neutral",
    contextHint: "A child looking in the pantry or at snacks on the counter, looking hopeful",
  },
  {
    id: "thirsty",
    label: "I'm thirsty",
    text: "I'm really thirsty. Can I have a drink please?",
    category: "Requests",
    color: "#f97316",
    icon: "thirsty",
    emotion: "neutral",
    contextHint: "A child reaching for a cup of water, looking thirsty",
  },
  {
    id: "help",
    label: "Help me",
    text: "I need some help with this. Can you show me how?",
    category: "Requests",
    color: "#f97316",
    icon: "help",
    emotion: "neutral",
    contextHint: "A child looking puzzled at a task, reaching out to an adult for assistance",
  },
  {
    id: "need-help",
    label: "I need help",
    text: "I need help with this please.",
    category: "Requests",
    color: "#f97316",
    icon: "help",
    emotion: "neutral",
    contextHint: "A child looking at something they can't do alone, reaching out for assistance",
  },
  // Commands
  {
    id: "stop",
    label: "Stop",
    text: "Please stop. I need you to stop right now.",
    category: "Commands",
    color: "#ef4444",
    icon: "stop",
    emotion: "frustrated",
    contextHint: "A child holding up their hand in a stop gesture, looking serious",
  },
  {
    id: "wait",
    label: "Wait",
    text: "Wait, hold on! I'm not ready yet.",
    category: "Commands",
    color: "#ef4444",
    icon: "wait",
    emotion: "neutral",
    contextHint: "A child gesturing to pause, needing a moment to get ready",
  },
  {
    id: "come-here",
    label: "Come here",
    text: "Come here please! I want to show you something.",
    category: "Commands",
    color: "#ef4444",
    icon: "wave",
    emotion: "excited",
    contextHint: "A child beckoning someone to come closer, excited to share something",
  },
  {
    id: "listen",
    label: "Listen",
    text: "Hey, listen to me for a second. This is important.",
    category: "Commands",
    color: "#ef4444",
    icon: "listen",
    emotion: "neutral",
    contextHint: "A child trying to get attention, cupping hands near their mouth",
  },
  // Refusals
  {
    id: "no-thanks",
    label: "No thank you",
    text: "No thank you, I don't want that right now.",
    category: "Refusals",
    color: "#8b5cf6",
    icon: "no",
    emotion: "calm",
    contextHint: "A child politely shaking their head, declining something offered",
  },
  {
    id: "im-done",
    label: "I'm done",
    text: "I'm all done now. I don't want any more.",
    category: "Refusals",
    color: "#8b5cf6",
    icon: "finished",
    emotion: "calm",
    contextHint: "A child pushing away their plate or stopping an activity, satisfied",
  },
  {
    id: "not-now",
    label: "Not now",
    text: "Not right now. Maybe later, okay?",
    category: "Refusals",
    color: "#8b5cf6",
    icon: "wait",
    emotion: "calm",
    contextHint: "A child gesturing 'later' while focused on something else",
  },
  {
    id: "break",
    label: "I need a break",
    text: "I need to take a break. This is too much right now.",
    category: "Refusals",
    color: "#8b5cf6",
    icon: "wait",
    emotion: "calm",
    contextHint: "A child sitting down to rest, taking deep breaths",
  },
  // Questions
  {
    id: "what-doing",
    label: "What's that?",
    text: "What is that? Can you tell me about it?",
    category: "Questions",
    color: "#3b82f6",
    icon: "what",
    emotion: "neutral",
    contextHint: "A curious child pointing at something unfamiliar, tilting their head",
  },
  {
    id: "where-going",
    label: "Where?",
    text: "Where are we going? I want to know!",
    category: "Questions",
    color: "#3b82f6",
    icon: "where",
    emotion: "excited",
    contextHint: "A child looking around curiously, wondering about the destination",
  },
  {
    id: "when",
    label: "When?",
    text: "When is it going to happen? I can't wait!",
    category: "Questions",
    color: "#3b82f6",
    icon: "when",
    emotion: "excited",
    contextHint: "An eager child checking the clock or calendar, anticipating something",
  },
  {
    id: "why",
    label: "Why?",
    text: "Why? I want to understand. Can you explain?",
    category: "Questions",
    color: "#3b82f6",
    icon: "why",
    emotion: "neutral",
    contextHint: "A thoughtful child with a questioning expression, seeking to learn",
  },
  // Feelings
  {
    id: "happy",
    label: "I'm happy",
    text: "I'm feeling so happy right now! This is great!",
    category: "Feelings",
    color: "#ec4899",
    icon: "happy",
    emotion: "happy",
    contextHint: "A joyful child with a big smile, arms spread wide in happiness",
  },
  {
    id: "sad",
    label: "I'm sad",
    text: "I'm feeling sad. I need a hug.",
    category: "Feelings",
    color: "#ec4899",
    icon: "sad",
    emotion: "sad",
    contextHint: "A sad child being comforted by a caring adult with a gentle hug",
  },
  {
    id: "tired",
    label: "I'm tired",
    text: "I'm tired. I need to rest.",
    category: "Feelings",
    color: "#ec4899",
    icon: "wait",
    emotion: "calm",
    contextHint: "A sleepy child rubbing their eyes, yawning, ready for bed",
  },
  {
    id: "love-you",
    label: "I love you",
    text: "I love you so much! You're the best!",
    category: "Feelings",
    color: "#ec4899",
    icon: "love",
    emotion: "happy",
    contextHint: "A child giving a warm hug to someone they love, hearts floating around",
  },
  {
    id: "good-night",
    label: "Good night",
    text: "Good night! Sleep well!",
    category: "Social",
    color: "#14b8a6",
    icon: "moon",
    emotion: "calm",
    contextHint: "A child in pajamas waving goodnight, getting into bed with a stuffed animal",
  },
  {
    id: "good-day",
    label: "I had a good day",
    text: "I had a good day today! It was fun!",
    category: "Feelings",
    color: "#ec4899",
    icon: "smile",
    emotion: "happy",
    contextHint: "A happy child at the end of the day, smiling about the fun things they did",
  },
]
